name: pytest-linux.yaml

on: [push]

env:
  PYTHONPATH: /home/runner/work/g2-sdk-python-abstract/g2-sdk-python-abstract/src

jobs:
  pytest-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8", "3.11"]
    name: "pytest OS: ${{ matrix.os }}; Python ${{ matrix.python-version }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
          python -m pip install psutil pytest pytest-cov pytest-schema
      - name: Run pytest on tests
        run: pytest tests/ --verbose --capture=no --cov=src/senzing_abstract
